name: "hacksu-website"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.khe-renaissance.rule=Host(`hacksu.com`)"
      - "traefik.http.routers.khe-renaissance.entrypoints=web"
      - "traefik.http.services.khe-renaissance.loadbalancer.server.port=8000"
      - "traefik.http.services.khe-renaissance.loadbalancer.server.scheme=http"
    networks:
      - traefik

networks:
  traefik:
    external: true